apiVersion: v1
kind: Service
metadata:
  name: deathstar-api
  labels:
    app: deathstar-api
spec:
  type: NodePort
  selector:
    app: deathstar-api
  ports:
    - name: http
      port: 80
      targetPort: 8081
      nodePort: 30007