name: CI - Deathstar API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Download dependencies
        run: go mod tidy

      - name: Vet
        run: go vet ./...

      # =========================
      # TESTES + COVERAGE (CORRIGIDO)
      # =========================
      - name: Run tests with coverage
        run: go test ./internal/service -v -coverprofile=coverage.out

      - name: Check coverage threshold (>=70%)
        run: |
          COVER=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | tr -d '%')
          echo "Coverage: $COVER%"

          if (( $(echo "$COVER < 70" | bc -l) )); then
            echo "Coverage abaixo de 70% (falha no CI)"
            exit 1
          fi

      # =========================
      # BUILD
      # =========================
      - name: Build
        run: go build -o api cmd/api/main.go

      # =========================
      # ARTIFACT (OPCIONAL)
      # =========================
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out